//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MixItUp.Base {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MixItUp.Base.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Groups.
        /// </summary>
        public static string ActionGroups {
            get {
                return ResourceManager.GetString("ActionGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Command.
        /// </summary>
        public static string AddCommand {
            get {
                return ResourceManager.GetString("AddCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user already exists in this group..
        /// </summary>
        public static string AddFavoriteStreamerAlreadyDone {
            get {
                return ResourceManager.GetString("AddFavoriteStreamerAlreadyDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a user by that name..
        /// </summary>
        public static string AddFavoriteStreamerNotFound {
            get {
                return ResourceManager.GetString("AddFavoriteStreamerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already favorited this team..
        /// </summary>
        public static string AddFavoriteTeamAlreadyDone {
            get {
                return ResourceManager.GetString("AddFavoriteTeamAlreadyDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a team by that name..
        /// </summary>
        public static string AddFavoriteTeamNotFound {
            get {
                return ResourceManager.GetString("AddFavoriteTeamNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Command.
        /// </summary>
        public static string AdvancedCommand {
            get {
                return ResourceManager.GetString("AdvancedCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age Rating.
        /// </summary>
        public static string AgeRating {
            get {
                return ResourceManager.GetString("AgeRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Donated.
        /// </summary>
        public static string AmountDonated {
            get {
                return ResourceManager.GetString("AmountDonated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audience.
        /// </summary>
        public static string Audience {
            get {
                return ResourceManager.GetString("Audience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-Hoster.
        /// </summary>
        public static string AutoHoster {
            get {
                return ResourceManager.GetString("AutoHoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Chat Command.
        /// </summary>
        public static string BasicChatCommand {
            get {
                return ResourceManager.GetString("BasicChatCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Sound Command.
        /// </summary>
        public static string BasicSoundCommand {
            get {
                return ResourceManager.GetString("BasicSoundCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot.
        /// </summary>
        public static string Bot {
            get {
                return ResourceManager.GetString("Bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        public static string Channel {
            get {
                return ResourceManager.GetString("Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Editor.
        /// </summary>
        public static string ChannelEditor {
            get {
                return ResourceManager.GetString("ChannelEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid age rating must be selected..
        /// </summary>
        public static string ChannelErrorInvalidAgeRating {
            get {
                return ResourceManager.GetString("ChannelErrorInvalidAgeRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid &amp; existing game name must be selected..
        /// </summary>
        public static string ChannelErrorInvalidGame {
            get {
                return ResourceManager.GetString("ChannelErrorInvalidGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A stream title must be specified..
        /// </summary>
        public static string ChannelErrorNoStreamTitle {
            get {
                return ResourceManager.GetString("ChannelErrorNoStreamTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Info.
        /// </summary>
        public static string ChannelInfo {
            get {
                return ResourceManager.GetString("ChannelInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Name.
        /// </summary>
        public static string ChannelName {
            get {
                return ResourceManager.GetString("ChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string Chat {
            get {
                return ResourceManager.GetString("Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Message.
        /// </summary>
        public static string ChatMessage {
            get {
                return ResourceManager.GetString("ChatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Messages Sent.
        /// </summary>
        public static string ChatMessagesSent {
            get {
                return ResourceManager.GetString("ChatMessagesSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Chat.
        /// </summary>
        public static string ClearChat {
            get {
                return ResourceManager.GetString("ClearChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will clear all chat messages for the stream. Are you sure?.
        /// </summary>
        public static string ClearChatConfirmation {
            get {
                return ResourceManager.GetString("ClearChatConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while Mix It Up saves your settings and shuts down....
        /// </summary>
        public static string ClosingPleaseWait {
            get {
                return ResourceManager.GetString("ClosingPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands.
        /// </summary>
        public static string Commands {
            get {
                return ResourceManager.GetString("Commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands Run.
        /// </summary>
        public static string CommandsRun {
            get {
                return ResourceManager.GetString("CommandsRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Devices.
        /// </summary>
        public static string ConnectDevices {
            get {
                return ResourceManager.GetString("ConnectDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cumulative Months Subbed.
        /// </summary>
        public static string CumulativeMonthsSubbed {
            get {
                return ResourceManager.GetString("CumulativeMonthsSubbed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency/Rank/Inventory.
        /// </summary>
        public static string CurrencyRankInventory {
            get {
                return ResourceManager.GetString("CurrencyRankInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency/Rank/Inventory Exempt.
        /// </summary>
        public static string CurrencyRankInventoryExempt {
            get {
                return ResourceManager.GetString("CurrencyRankInventoryExempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Commands.
        /// </summary>
        public static string CustomCommands {
            get {
                return ResourceManager.GetString("CustomCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Entrance Command.
        /// </summary>
        public static string CustomEntranceCommand {
            get {
                return ResourceManager.GetString("CustomEntranceCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize Command.
        /// </summary>
        public static string CustomizeCommand {
            get {
                return ResourceManager.GetString("CustomizeCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Title.
        /// </summary>
        public static string CustomTitle {
            get {
                return ResourceManager.GetString("CustomTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Command.
        /// </summary>
        public static string DeleteCommand {
            get {
                return ResourceManager.GetString("DeleteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to remove this group?.
        /// </summary>
        public static string DeleteFavoriteGroupConfirmation {
            get {
                return ResourceManager.GetString("DeleteFavoriteGroupConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable All Timers.
        /// </summary>
        public static string DisableAllTimers {
            get {
                return ResourceManager.GetString("DisableAllTimers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Chat.
        /// </summary>
        public static string DisableChat {
            get {
                return ResourceManager.GetString("DisableChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will disable chat for all users. Are you sure?.
        /// </summary>
        public static string DisableChatConfirmation {
            get {
                return ResourceManager.GetString("DisableChatConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DownloadFrom.
        /// </summary>
        public static string DownloadFrom {
            get {
                return ResourceManager.GetString("DownloadFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Command.
        /// </summary>
        public static string EditCommand {
            get {
                return ResourceManager.GetString("EditCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embers Spent.
        /// </summary>
        public static string EmbersSpent {
            get {
                return ResourceManager.GetString("EmbersSpent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Chat.
        /// </summary>
        public static string EnableChat {
            get {
                return ResourceManager.GetString("EnableChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable/Disable Command.
        /// </summary>
        public static string EnableDisableCommand {
            get {
                return ResourceManager.GetString("EnableDisableCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be a {0} to pick the answer..
        /// </summary>
        public static string ErrorGamePickInsufficientRole {
            get {
                return ResourceManager.GetString("ErrorGamePickInsufficientRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be a {0} to start this game..
        /// </summary>
        public static string ErrorGameStartInsufficentRole {
            get {
                return ResourceManager.GetString("ErrorGameStartInsufficentRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to exit Mix It Up?.
        /// </summary>
        public static string ExitConfirmation {
            get {
                return ResourceManager.GetString("ExitConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Data.
        /// </summary>
        public static string ExportData {
            get {
                return ResourceManager.GetString("ExportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        public static string Family {
            get {
                return ResourceManager.GetString("Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorited Users/Teams.
        /// </summary>
        public static string FavoritedUsersTeams {
            get {
                return ResourceManager.GetString("FavoritedUsersTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite Streamers.
        /// </summary>
        public static string FavoriteStreamers {
            get {
                return ResourceManager.GetString("FavoriteStreamers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter By Name.
        /// </summary>
        public static string FilterByName {
            get {
                return ResourceManager.GetString("FilterByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Channel To Raid.
        /// </summary>
        public static string FindChannelToRaid {
            get {
                return ResourceManager.GetString("FindChannelToRaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must select a search criteria for finding a channel to raid..
        /// </summary>
        public static string FindRaidErrorNoCriteria {
            get {
                return ResourceManager.GetString("FindRaidErrorNoCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find a channel that met your search critera, please try selecting a different option..
        /// </summary>
        public static string FindRaidErrorNoneFound {
            get {
                return ResourceManager.GetString("FindRaidErrorNoneFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Age.
        /// </summary>
        public static string FollowAge {
            get {
                return ResourceManager.GetString("FollowAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follower.
        /// </summary>
        public static string Follower {
            get {
                return ResourceManager.GetString("Follower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        public static string Game {
            get {
                return ResourceManager.GetString("Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Name.
        /// </summary>
        public static string GameName {
            get {
                return ResourceManager.GetString("GameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Queue.
        /// </summary>
        public static string GameQueue {
            get {
                return ResourceManager.GetString("GameQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        public static string Games {
            get {
                return ResourceManager.GetString("Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giveaway.
        /// </summary>
        public static string Giveaway {
            get {
                return ResourceManager.GetString("Giveaway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name.
        /// </summary>
        public static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Channel.
        /// </summary>
        public static string HostChannel {
            get {
                return ResourceManager.GetString("HostChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Data.
        /// </summary>
        public static string ImportData {
            get {
                return ResourceManager.GetString("ImportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Streamer (&gt;25).
        /// </summary>
        public static string LargeStreamer {
            get {
                return ResourceManager.GetString("LargeStreamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Agreement.
        /// </summary>
        public static string LicenseAgreement {
            get {
                return ResourceManager.GetString("LicenseAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live.
        /// </summary>
        public static string Live {
            get {
                return ResourceManager.GetString("Live", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock/Unlock Chat Scrolling.
        /// </summary>
        public static string LockChatScrolling {
            get {
                return ResourceManager.GetString("LockChatScrolling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot Account failed to authenticate, please re-connect it from the Services section..
        /// </summary>
        public static string LoginErrorBotAccountFailed {
            get {
                return ResourceManager.GetString("LoginErrorBotAccountFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to authenticate with Mixer, please try again..
        /// </summary>
        public static string LoginErrorFailedToAuthenticate {
            get {
                return ResourceManager.GetString("LoginErrorFailedToAuthenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A channel name must be entered..
        /// </summary>
        public static string LoginErrorNoChannelName {
            get {
                return ResourceManager.GetString("LoginErrorNoChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a Streamer account to log in to..
        /// </summary>
        public static string LoginErrorNoStreamerAccount {
            get {
                return ResourceManager.GetString("LoginErrorNoStreamerAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not a moderator for this channel..
        /// </summary>
        public static string LoginErrorNotModerator {
            get {
                return ResourceManager.GetString("LoginErrorNotModerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Streamer (10-25).
        /// </summary>
        public static string MediumStreamer {
            get {
                return ResourceManager.GetString("MediumStreamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Messages.
        /// </summary>
        public static string MinMessages {
            get {
                return ResourceManager.GetString("MinMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixer Data.
        /// </summary>
        public static string MixerData {
            get {
                return ResourceManager.GetString("MixerData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixer Labs.
        /// </summary>
        public static string MixerLabs {
            get {
                return ResourceManager.GetString("MixerLabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MixPlay.
        /// </summary>
        public static string MixPlay {
            get {
                return ResourceManager.GetString("MixPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod.
        /// </summary>
        public static string Mod {
            get {
                return ResourceManager.GetString("Mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderation.
        /// </summary>
        public static string Moderation {
            get {
                return ResourceManager.GetString("Moderation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderator.
        /// </summary>
        public static string Moderator {
            get {
                return ResourceManager.GetString("Moderator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Months.
        /// </summary>
        public static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Profile.
        /// </summary>
        public static string NameOfProfile {
            get {
                return ResourceManager.GetString("NameOfProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewActionGroup.
        /// </summary>
        public static string NewActionGroup {
            get {
                return ResourceManager.GetString("NewActionGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Command.
        /// </summary>
        public static string NewCommand {
            get {
                return ResourceManager.GetString("NewCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Streamer.
        /// </summary>
        public static string NewStreamer {
            get {
                return ResourceManager.GetString("NewStreamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Minutes.
        /// </summary>
        public static string OnlineMinutes {
            get {
                return ResourceManager.GetString("OnlineMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay.
        /// </summary>
        public static string Overlay {
            get {
                return ResourceManager.GetString("Overlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay Widgets.
        /// </summary>
        public static string OverlayWidgets {
            get {
                return ResourceManager.GetString("OverlayWidgets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner.
        /// </summary>
        public static string Partner {
            get {
                return ResourceManager.GetString("Partner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partnered Streamer.
        /// </summary>
        public static string PartneredStreamer {
            get {
                return ResourceManager.GetString("PartneredStreamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patreon User.
        /// </summary>
        public static string PatreonUser {
            get {
                return ResourceManager.GetString("PatreonUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pos.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Made Commands.
        /// </summary>
        public static string PreMadeCommands {
            get {
                return ResourceManager.GetString("PreMadeCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Currency.
        /// </summary>
        public static string PrimaryCurrency {
            get {
                return ResourceManager.GetString("PrimaryCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Rank.
        /// </summary>
        public static string PrimaryRank {
            get {
                return ResourceManager.GetString("PrimaryRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pro.
        /// </summary>
        public static string Pro {
            get {
                return ResourceManager.GetString("Pro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        public static string Profiles {
            get {
                return ResourceManager.GetString("Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotes.
        /// </summary>
        public static string Quotes {
            get {
                return ResourceManager.GetString("Quotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Streamer.
        /// </summary>
        public static string RandomStreamer {
            get {
                return ResourceManager.GetString("RandomStreamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular.
        /// </summary>
        public static string Regular {
            get {
                return ResourceManager.GetString("Regular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote.
        /// </summary>
        public static string Remote {
            get {
                return ResourceManager.GetString("Remote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be a {0} to do this..
        /// </summary>
        public static string RoleErrorInsufficientRole {
            get {
                return ResourceManager.GetString("RoleErrorInsufficientRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same Age Rating.
        /// </summary>
        public static string SameAgeRating {
            get {
                return ResourceManager.GetString("SameAgeRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same Game.
        /// </summary>
        public static string SameGame {
            get {
                return ResourceManager.GetString("SameGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SameTeam.
        /// </summary>
        public static string SameTeam {
            get {
                return ResourceManager.GetString("SameTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save failed, attempting one more time....
        /// </summary>
        public static string SaveFailed {
            get {
                return ResourceManager.GetString("SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scene.
        /// </summary>
        public static string Scene {
            get {
                return ResourceManager.GetString("Scene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Criteria.
        /// </summary>
        public static string SearchCriteria {
            get {
                return ResourceManager.GetString("SearchCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the type of command you would like to build:.
        /// </summary>
        public static string SelectTypeOfCommand {
            get {
                return ResourceManager.GetString("SelectTypeOfCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills Used.
        /// </summary>
        public static string SkillsUsed {
            get {
                return ResourceManager.GetString("SkillsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Streamer (&lt;10).
        /// </summary>
        public static string SmallStreamer {
            get {
                return ResourceManager.GetString("SmallStreamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spark Exempt.
        /// </summary>
        public static string SparkExempt {
            get {
                return ResourceManager.GetString("SparkExempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sparks Spent.
        /// </summary>
        public static string SparksSpent {
            get {
                return ResourceManager.GetString("SparksSpent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        public static string Staff {
            get {
                return ResourceManager.GetString("Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streamer.
        /// </summary>
        public static string Streamer {
            get {
                return ResourceManager.GetString("Streamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streamer Account.
        /// </summary>
        public static string StreamerAccount {
            get {
                return ResourceManager.GetString("StreamerAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streams Watched.
        /// </summary>
        public static string StreamsWatched {
            get {
                return ResourceManager.GetString("StreamsWatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream Title.
        /// </summary>
        public static string StreamTitle {
            get {
                return ResourceManager.GetString("StreamTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Age.
        /// </summary>
        public static string SubAge {
            get {
                return ResourceManager.GetString("SubAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriber.
        /// </summary>
        public static string Subscriber {
            get {
                return ResourceManager.GetString("Subscriber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subs Gifted.
        /// </summary>
        public static string SubsGifted {
            get {
                return ResourceManager.GetString("SubsGifted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subs Received.
        /// </summary>
        public static string SubsReceived {
            get {
                return ResourceManager.GetString("SubsReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagged In Chat.
        /// </summary>
        public static string TaggedInChat {
            get {
                return ResourceManager.GetString("TaggedInChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Name.
        /// </summary>
        public static string TeamName {
            get {
                return ResourceManager.GetString("TeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teen.
        /// </summary>
        public static string Teen {
            get {
                return ResourceManager.GetString("Teen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Command.
        /// </summary>
        public static string TestCommand {
            get {
                return ResourceManager.GetString("TestCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval (Minutes).
        /// </summary>
        public static string TimerInterval {
            get {
                return ResourceManager.GetString("TimerInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timers.
        /// </summary>
        public static string Timers {
            get {
                return ResourceManager.GetString("Timers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Users.
        /// </summary>
        public static string TotalUsers {
            get {
                return ResourceManager.GetString("TotalUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TranslationBy {
            get {
                return ResourceManager.GetString("TranslationBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type To Add.
        /// </summary>
        public static string TypeToAdd {
            get {
                return ResourceManager.GetString("TypeToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungrouped.
        /// </summary>
        public static string Ungrouped {
            get {
                return ResourceManager.GetString("Ungrouped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Channel.
        /// </summary>
        public static string UpdateChannel {
            get {
                return ResourceManager.GetString("UpdateChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Joined Chat.
        /// </summary>
        public static string UserJoinedChat {
            get {
                return ResourceManager.GetString("UserJoinedChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Left Chat.
        /// </summary>
        public static string UserLeftChat {
            get {
                return ResourceManager.GetString("UserLeftChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Metrics.
        /// </summary>
        public static string UserMetrics {
            get {
                return ResourceManager.GetString("UserMetrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-Only Chat Commands.
        /// </summary>
        public static string UserOnlyChatCommands {
            get {
                return ResourceManager.GetString("UserOnlyChatCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewers.
        /// </summary>
        public static string Viewers {
            get {
                return ResourceManager.GetString("Viewers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch Time.
        /// </summary>
        public static string WatchTime {
            get {
                return ResourceManager.GetString("WatchTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Show.
        /// </summary>
        public static string WebShow {
            get {
                return ResourceManager.GetString("WebShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
