//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MixItUp.Base {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MixItUp.Base.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Per Ember.
        /// </summary>
        public static string _1PerEmber {
            get {
                return ResourceManager.GetString("1PerEmber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Per Hour.
        /// </summary>
        public static string _1PerHour {
            get {
                return ResourceManager.GetString("1PerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Per Minute.
        /// </summary>
        public static string _1PerMinute {
            get {
                return ResourceManager.GetString("1PerMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Per Spark.
        /// </summary>
        public static string _1PerSpark {
            get {
                return ResourceManager.GetString("1PerSpark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquire Rate.
        /// </summary>
        public static string AcquireRate {
            get {
                return ResourceManager.GetString("AcquireRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Group.
        /// </summary>
        public static string ActionGroup {
            get {
                return ResourceManager.GetString("ActionGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Groups.
        /// </summary>
        public static string ActionGroups {
            get {
                return ResourceManager.GetString("ActionGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Clause.
        /// </summary>
        public static string AddClause {
            get {
                return ResourceManager.GetString("AddClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Command.
        /// </summary>
        public static string AddCommand {
            get {
                return ResourceManager.GetString("AddCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Currency/Rank.
        /// </summary>
        public static string AddCurrencyRank {
            get {
                return ResourceManager.GetString("AddCurrencyRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user already exists in this group..
        /// </summary>
        public static string AddFavoriteStreamerAlreadyDone {
            get {
                return ResourceManager.GetString("AddFavoriteStreamerAlreadyDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a user by that name..
        /// </summary>
        public static string AddFavoriteStreamerNotFound {
            get {
                return ResourceManager.GetString("AddFavoriteStreamerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already favorited this team..
        /// </summary>
        public static string AddFavoriteTeamAlreadyDone {
            get {
                return ResourceManager.GetString("AddFavoriteTeamAlreadyDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a team by that name..
        /// </summary>
        public static string AddFavoriteTeamNotFound {
            get {
                return ResourceManager.GetString("AddFavoriteTeamNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Inventory.
        /// </summary>
        public static string AddInventory {
            get {
                return ResourceManager.GetString("AddInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Item.
        /// </summary>
        public static string AddItem {
            get {
                return ResourceManager.GetString("AddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Rank.
        /// </summary>
        public static string AddNewRank {
            get {
                return ResourceManager.GetString("AddNewRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Overlay Widget.
        /// </summary>
        public static string AddOverlayWidget {
            get {
                return ResourceManager.GetString("AddOverlayWidget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Command.
        /// </summary>
        public static string AdvancedCommand {
            get {
                return ResourceManager.GetString("AdvancedCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age Rating.
        /// </summary>
        public static string AgeRating {
            get {
                return ResourceManager.GetString("AgeRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Donated.
        /// </summary>
        public static string AmountDonated {
            get {
                return ResourceManager.GetString("AmountDonated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audience.
        /// </summary>
        public static string Audience {
            get {
                return ResourceManager.GetString("Audience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-Hoster.
        /// </summary>
        public static string AutoHoster {
            get {
                return ResourceManager.GetString("AutoHoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-Include &quot;!&quot;.
        /// </summary>
        public static string AutoIncludeBang {
            get {
                return ResourceManager.GetString("AutoIncludeBang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Reset.
        /// </summary>
        public static string AutomaticReset {
            get {
                return ResourceManager.GetString("AutomaticReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Color.
        /// </summary>
        public static string BackgroundColor {
            get {
                return ResourceManager.GetString("BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Chat Command.
        /// </summary>
        public static string BasicChatCommand {
            get {
                return ResourceManager.GetString("BasicChatCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Sound Command.
        /// </summary>
        public static string BasicSoundCommand {
            get {
                return ResourceManager.GetString("BasicSoundCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What should we call this Timer command?.
        /// </summary>
        public static string BasicTimerDescription {
            get {
                return ResourceManager.GetString("BasicTimerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (EX: &quot;Follow Me&quot;).
        /// </summary>
        public static string BasicTimerNameHint {
            get {
                return ResourceManager.GetString("BasicTimerNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Between.
        /// </summary>
        public static string Between {
            get {
                return ResourceManager.GetString("Between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot.
        /// </summary>
        public static string Bot {
            get {
                return ResourceManager.GetString("Bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button Name.
        /// </summary>
        public static string ButtonName {
            get {
                return ResourceManager.GetString("ButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Price.
        /// </summary>
        public static string BuyPrice {
            get {
                return ResourceManager.GetString("BuyPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Sensitive.
        /// </summary>
        public static string CaseSensitive {
            get {
                return ResourceManager.GetString("CaseSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        public static string Channel {
            get {
                return ResourceManager.GetString("Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Editor.
        /// </summary>
        public static string ChannelEditor {
            get {
                return ResourceManager.GetString("ChannelEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid age rating must be selected..
        /// </summary>
        public static string ChannelErrorInvalidAgeRating {
            get {
                return ResourceManager.GetString("ChannelErrorInvalidAgeRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid &amp; existing game name must be selected..
        /// </summary>
        public static string ChannelErrorInvalidGame {
            get {
                return ResourceManager.GetString("ChannelErrorInvalidGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A stream title must be specified..
        /// </summary>
        public static string ChannelErrorNoStreamTitle {
            get {
                return ResourceManager.GetString("ChannelErrorNoStreamTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Info.
        /// </summary>
        public static string ChannelInfo {
            get {
                return ResourceManager.GetString("ChannelInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Name.
        /// </summary>
        public static string ChannelName {
            get {
                return ResourceManager.GetString("ChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string Chat {
            get {
                return ResourceManager.GetString("Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Message.
        /// </summary>
        public static string ChatMessage {
            get {
                return ResourceManager.GetString("ChatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Messages.
        /// </summary>
        public static string ChatMessages {
            get {
                return ResourceManager.GetString("ChatMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Messages Sent.
        /// </summary>
        public static string ChatMessagesSent {
            get {
                return ResourceManager.GetString("ChatMessagesSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Chat.
        /// </summary>
        public static string ClearChat {
            get {
                return ResourceManager.GetString("ClearChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will clear all chat messages for the stream. Are you sure?.
        /// </summary>
        public static string ClearChatConfirmation {
            get {
                return ResourceManager.GetString("ClearChatConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while Mix It Up saves your settings and shuts down....
        /// </summary>
        public static string ClosingPleaseWait {
            get {
                return ResourceManager.GetString("ClosingPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        public static string Command {
            get {
                return ResourceManager.GetString("Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Group.
        /// </summary>
        public static string CommandGroup {
            get {
                return ResourceManager.GetString("CommandGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands.
        /// </summary>
        public static string Commands {
            get {
                return ResourceManager.GetString("Commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands Run.
        /// </summary>
        public static string CommandsRun {
            get {
                return ResourceManager.GetString("CommandsRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare.
        /// </summary>
        public static string Compare {
            get {
                return ResourceManager.GetString("Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditional.
        /// </summary>
        public static string Conditional {
            get {
                return ResourceManager.GetString("Conditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Devices.
        /// </summary>
        public static string ConnectDevices {
            get {
                return ResourceManager.GetString("ConnectDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        public static string Contains {
            get {
                return ResourceManager.GetString("Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert To Advanced.
        /// </summary>
        public static string ConvertToAdvanced {
            get {
                return ResourceManager.GetString("ConvertToAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter (Create &amp; Update).
        /// </summary>
        public static string CounterCreateAndUpdate {
            get {
                return ResourceManager.GetString("CounterCreateAndUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cumulative Months Subbed.
        /// </summary>
        public static string CumulativeMonthsSubbed {
            get {
                return ResourceManager.GetString("CumulativeMonthsSubbed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currencies/Ranks/Inventories.
        /// </summary>
        public static string CurrenciesRanksInventories {
            get {
                return ResourceManager.GetString("CurrenciesRanksInventories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency/Rank.
        /// </summary>
        public static string CurrencyRank {
            get {
                return ResourceManager.GetString("CurrencyRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency/Rank/Inventory.
        /// </summary>
        public static string CurrencyRankInventory {
            get {
                return ResourceManager.GetString("CurrencyRankInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency/Rank/Inventory Exempt.
        /// </summary>
        public static string CurrencyRankInventoryExempt {
            get {
                return ResourceManager.GetString("CurrencyRankInventoryExempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency/Rank Name.
        /// </summary>
        public static string CurrencyRankName {
            get {
                return ResourceManager.GetString("CurrencyRankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Commands.
        /// </summary>
        public static string CustomCommands {
            get {
                return ResourceManager.GetString("CustomCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Entrance Command.
        /// </summary>
        public static string CustomEntranceCommand {
            get {
                return ResourceManager.GetString("CustomEntranceCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize Command.
        /// </summary>
        public static string CustomizeCommand {
            get {
                return ResourceManager.GetString("CustomizeCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize Currency/Rank.
        /// </summary>
        public static string CustomizeCurrencyRank {
            get {
                return ResourceManager.GetString("CustomizeCurrencyRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize Inventory.
        /// </summary>
        public static string CustomizeInventory {
            get {
                return ResourceManager.GetString("CustomizeInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Title.
        /// </summary>
        public static string CustomTitle {
            get {
                return ResourceManager.GetString("CustomTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        public static string Daily {
            get {
                return ResourceManager.GetString("Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Max Amount.
        /// </summary>
        public static string DefaultMaxAmount {
            get {
                return ResourceManager.GetString("DefaultMaxAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Command.
        /// </summary>
        public static string DeleteCommand {
            get {
                return ResourceManager.GetString("DeleteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to remove this group?.
        /// </summary>
        public static string DeleteFavoriteGroupConfirmation {
            get {
                return ResourceManager.GetString("DeleteFavoriteGroupConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable All Timers.
        /// </summary>
        public static string DisableAllTimers {
            get {
                return ResourceManager.GetString("DisableAllTimers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Chat.
        /// </summary>
        public static string DisableChat {
            get {
                return ResourceManager.GetString("DisableChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will disable chat for all users. Are you sure?.
        /// </summary>
        public static string DisableChatConfirmation {
            get {
                return ResourceManager.GetString("DisableChatConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord.
        /// </summary>
        public static string Discord {
            get {
                return ResourceManager.GetString("Discord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&gt; Contains.
        /// </summary>
        public static string DoesNotContain {
            get {
                return ResourceManager.GetString("DoesNotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DownloadFrom.
        /// </summary>
        public static string DownloadFrom {
            get {
                return ResourceManager.GetString("DownloadFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Command.
        /// </summary>
        public static string EditCommand {
            get {
                return ResourceManager.GetString("EditCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embers Spent.
        /// </summary>
        public static string EmbersSpent {
            get {
                return ResourceManager.GetString("EmbersSpent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Chat.
        /// </summary>
        public static string EnableChat {
            get {
                return ResourceManager.GetString("EnableChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable/Disable Command.
        /// </summary>
        public static string EnableDisableCommand {
            get {
                return ResourceManager.GetString("EnableDisableCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Credits.
        /// </summary>
        public static string EndCredits {
            get {
                return ResourceManager.GetString("EndCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =.
        /// </summary>
        public static string EqualsCompare {
            get {
                return ResourceManager.GetString("EqualsCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be a {0} to pick the answer..
        /// </summary>
        public static string ErrorGamePickInsufficientRole {
            get {
                return ResourceManager.GetString("ErrorGamePickInsufficientRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be a {0} to start this game..
        /// </summary>
        public static string ErrorGameStartInsufficentRole {
            get {
                return ResourceManager.GetString("ErrorGameStartInsufficentRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        public static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Bonuses.
        /// </summary>
        public static string EventBonuses {
            get {
                return ResourceManager.GetString("EventBonuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event List.
        /// </summary>
        public static string EventList {
            get {
                return ResourceManager.GetString("EventList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to exit Mix It Up?.
        /// </summary>
        public static string ExitConfirmation {
            get {
                return ResourceManager.GetString("ExitConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Actions to File.
        /// </summary>
        public static string ExportActions {
            get {
                return ResourceManager.GetString("ExportActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Data.
        /// </summary>
        public static string ExportData {
            get {
                return ResourceManager.GetString("ExportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Program.
        /// </summary>
        public static string ExternalProgram {
            get {
                return ResourceManager.GetString("ExternalProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        public static string Family {
            get {
                return ResourceManager.GetString("Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fan Progression.
        /// </summary>
        public static string FanProgression {
            get {
                return ResourceManager.GetString("FanProgression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorited Users/Teams.
        /// </summary>
        public static string FavoritedUsersTeams {
            get {
                return ResourceManager.GetString("FavoritedUsersTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite Streamers.
        /// </summary>
        public static string FavoriteStreamers {
            get {
                return ResourceManager.GetString("FavoriteStreamers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File (Read &amp; Write).
        /// </summary>
        public static string FileReadAndWrite {
            get {
                return ResourceManager.GetString("FileReadAndWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter By Name.
        /// </summary>
        public static string FilterByName {
            get {
                return ResourceManager.GetString("FilterByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Channel To Raid.
        /// </summary>
        public static string FindChannelToRaid {
            get {
                return ResourceManager.GetString("FindChannelToRaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must select a search criteria for finding a channel to raid..
        /// </summary>
        public static string FindRaidErrorNoCriteria {
            get {
                return ResourceManager.GetString("FindRaidErrorNoCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find a channel that met your search critera, please try selecting a different option..
        /// </summary>
        public static string FindRaidErrorNoneFound {
            get {
                return ResourceManager.GetString("FindRaidErrorNoneFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Value.
        /// </summary>
        public static string FirstValue {
            get {
                return ResourceManager.GetString("FirstValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Age.
        /// </summary>
        public static string FollowAge {
            get {
                return ResourceManager.GetString("FollowAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follower.
        /// </summary>
        public static string Follower {
            get {
                return ResourceManager.GetString("Follower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        public static string Game {
            get {
                return ResourceManager.GetString("Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Name.
        /// </summary>
        public static string GameName {
            get {
                return ResourceManager.GetString("GameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Queue.
        /// </summary>
        public static string GameQueue {
            get {
                return ResourceManager.GetString("GameQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        public static string Games {
            get {
                return ResourceManager.GetString("Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giveaway.
        /// </summary>
        public static string Giveaway {
            get {
                return ResourceManager.GetString("Giveaway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        public static string GreaterThan {
            get {
                return ResourceManager.GetString("GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;=.
        /// </summary>
        public static string GreaterThanOrEqual {
            get {
                return ResourceManager.GetString("GreaterThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Interval (Min).
        /// </summary>
        public static string GroupIntervalMin {
            get {
                return ResourceManager.GetString("GroupIntervalMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name.
        /// </summary>
        public static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Channel.
        /// </summary>
        public static string HostChannel {
            get {
                return ResourceManager.GetString("HostChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML.
        /// </summary>
        public static string HTML {
            get {
                return ResourceManager.GetString("HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFTTT.
        /// </summary>
        public static string IFTTT {
            get {
                return ResourceManager.GetString("IFTTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Actions to File.
        /// </summary>
        public static string ImportActions {
            get {
                return ResourceManager.GetString("ImportActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Data.
        /// </summary>
        public static string ImportData {
            get {
                return ResourceManager.GetString("ImportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input (Keyboard &amp; Mouse).
        /// </summary>
        public static string InputKeyboardAndMouse {
            get {
                return ResourceManager.GetString("InputKeyboardAndMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        public static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Name.
        /// </summary>
        public static string InventoryName {
            get {
                return ResourceManager.GetString("InventoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Primary.
        /// </summary>
        public static string IsPrimary {
            get {
                return ResourceManager.GetString("IsPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Rank System.
        /// </summary>
        public static string IsRankSystem {
            get {
                return ResourceManager.GetString("IsRankSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item List.
        /// </summary>
        public static string ItemList {
            get {
                return ResourceManager.GetString("ItemList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        public static string ItemName {
            get {
                return ResourceManager.GetString("ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items Bought.
        /// </summary>
        public static string ItemsBought {
            get {
                return ResourceManager.GetString("ItemsBought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items Sold.
        /// </summary>
        public static string ItemsSold {
            get {
                return ResourceManager.GetString("ItemsSold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items Traded.
        /// </summary>
        public static string ItemsTraded {
            get {
                return ResourceManager.GetString("ItemsTraded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Streamer (&gt;25).
        /// </summary>
        public static string LargeStreamer {
            get {
                return ResourceManager.GetString("LargeStreamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaderboard.
        /// </summary>
        public static string Leaderboard {
            get {
                return ResourceManager.GetString("Leaderboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        public static string LessThan {
            get {
                return ResourceManager.GetString("LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;=.
        /// </summary>
        public static string LessThanOrEqual {
            get {
                return ResourceManager.GetString("LessThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Agreement.
        /// </summary>
        public static string LicenseAgreement {
            get {
                return ResourceManager.GetString("LicenseAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live.
        /// </summary>
        public static string Live {
            get {
                return ResourceManager.GetString("Live", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock/Unlock Chat Scrolling.
        /// </summary>
        public static string LockChatScrolling {
            get {
                return ResourceManager.GetString("LockChatScrolling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot Account failed to authenticate, please re-connect it from the Services section..
        /// </summary>
        public static string LoginErrorBotAccountFailed {
            get {
                return ResourceManager.GetString("LoginErrorBotAccountFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to authenticate with Mixer, please try again..
        /// </summary>
        public static string LoginErrorFailedToAuthenticate {
            get {
                return ResourceManager.GetString("LoginErrorFailedToAuthenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A channel name must be entered..
        /// </summary>
        public static string LoginErrorNoChannelName {
            get {
                return ResourceManager.GetString("LoginErrorNoChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a Streamer account to log in to..
        /// </summary>
        public static string LoginErrorNoStreamerAccount {
            get {
                return ResourceManager.GetString("LoginErrorNoStreamerAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not a moderator for this channel..
        /// </summary>
        public static string LoginErrorNotModerator {
            get {
                return ResourceManager.GetString("LoginErrorNotModerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Reset.
        /// </summary>
        public static string ManualReset {
            get {
                return ResourceManager.GetString("ManualReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Amount.
        /// </summary>
        public static string MaxAmount {
            get {
                return ResourceManager.GetString("MaxAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Streamer (10-25).
        /// </summary>
        public static string MediumStreamer {
            get {
                return ResourceManager.GetString("MediumStreamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Channel Activity (Mins).
        /// </summary>
        public static string MinimumChannelActivityMins {
            get {
                return ResourceManager.GetString("MinimumChannelActivityMins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Messages.
        /// </summary>
        public static string MinMessages {
            get {
                return ResourceManager.GetString("MinMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Points.
        /// </summary>
        public static string MinPoints {
            get {
                return ResourceManager.GetString("MinPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixer Clips.
        /// </summary>
        public static string MixerClips {
            get {
                return ResourceManager.GetString("MixerClips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixer Data.
        /// </summary>
        public static string MixerData {
            get {
                return ResourceManager.GetString("MixerData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixer Labs.
        /// </summary>
        public static string MixerLabs {
            get {
                return ResourceManager.GetString("MixerLabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MixPlay.
        /// </summary>
        public static string MixPlay {
            get {
                return ResourceManager.GetString("MixPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod.
        /// </summary>
        public static string Mod {
            get {
                return ResourceManager.GetString("Mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Bonus.
        /// </summary>
        public static string ModBonus {
            get {
                return ResourceManager.GetString("ModBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderation.
        /// </summary>
        public static string Moderation {
            get {
                return ResourceManager.GetString("Moderation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderator.
        /// </summary>
        public static string Moderator {
            get {
                return ResourceManager.GetString("Moderator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Months.
        /// </summary>
        public static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        public static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        public static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Profile.
        /// </summary>
        public static string NameOfProfile {
            get {
                return ResourceManager.GetString("NameOfProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string Never {
            get {
                return ResourceManager.GetString("Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewActionGroup.
        /// </summary>
        public static string NewActionGroup {
            get {
                return ResourceManager.GetString("NewActionGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Command.
        /// </summary>
        public static string NewCommand {
            get {
                return ResourceManager.GetString("NewCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Streamer.
        /// </summary>
        public static string NewStreamer {
            get {
                return ResourceManager.GetString("NewStreamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&gt;.
        /// </summary>
        public static string NotEquals {
            get {
                return ResourceManager.GetString("NotEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline Rate.
        /// </summary>
        public static string OfflineRate {
            get {
                return ResourceManager.GetString("OfflineRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Follow.
        /// </summary>
        public static string OnFollow {
            get {
                return ResourceManager.GetString("OnFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Host.
        /// </summary>
        public static string OnHost {
            get {
                return ResourceManager.GetString("OnHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Minutes.
        /// </summary>
        public static string OnlineMinutes {
            get {
                return ResourceManager.GetString("OnlineMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Rate.
        /// </summary>
        public static string OnlineRate {
            get {
                return ResourceManager.GetString("OnlineRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Subscribe.
        /// </summary>
        public static string OnSubscribe {
            get {
                return ResourceManager.GetString("OnSubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On User Rank Changed.
        /// </summary>
        public static string OnUserRankChanged {
            get {
                return ResourceManager.GetString("OnUserRankChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        public static string Operator {
            get {
                return ResourceManager.GetString("Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay.
        /// </summary>
        public static string Overlay {
            get {
                return ResourceManager.GetString("Overlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay (Images &amp; Videos).
        /// </summary>
        public static string OverlayImagesAndVideos {
            get {
                return ResourceManager.GetString("OverlayImagesAndVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay Widget - Editor.
        /// </summary>
        public static string OverlayWidgetEditor {
            get {
                return ResourceManager.GetString("OverlayWidgetEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Overlay Type you would like to create:.
        /// </summary>
        public static string OverlayWidgetEditorInstructions {
            get {
                return ResourceManager.GetString("OverlayWidgetEditorInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay Widgets.
        /// </summary>
        public static string OverlayWidgets {
            get {
                return ResourceManager.GetString("OverlayWidgets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Overlay must be enabled in the Services menu to use Overlay Widgets..
        /// </summary>
        public static string OverlayWidgetsRequireOverlay {
            get {
                return ResourceManager.GetString("OverlayWidgetsRequireOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OvrStream.
        /// </summary>
        public static string OvrStream {
            get {
                return ResourceManager.GetString("OvrStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner.
        /// </summary>
        public static string Partner {
            get {
                return ResourceManager.GetString("Partner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partnered Streamer.
        /// </summary>
        public static string PartneredStreamer {
            get {
                return ResourceManager.GetString("PartneredStreamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patreon User.
        /// </summary>
        public static string PatreonUser {
            get {
                return ResourceManager.GetString("PatreonUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pos.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Made Commands.
        /// </summary>
        public static string PreMadeCommands {
            get {
                return ResourceManager.GetString("PreMadeCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Currency.
        /// </summary>
        public static string PrimaryCurrency {
            get {
                return ResourceManager.GetString("PrimaryCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Rank.
        /// </summary>
        public static string PrimaryRank {
            get {
                return ResourceManager.GetString("PrimaryRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pro.
        /// </summary>
        public static string Pro {
            get {
                return ResourceManager.GetString("Pro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        public static string Profiles {
            get {
                return ResourceManager.GetString("Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal/Progress Bar.
        /// </summary>
        public static string ProgressBar {
            get {
                return ResourceManager.GetString("ProgressBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotes.
        /// </summary>
        public static string Quotes {
            get {
                return ResourceManager.GetString("Quotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Streamer.
        /// </summary>
        public static string RandomStreamer {
            get {
                return ResourceManager.GetString("RandomStreamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank Name.
        /// </summary>
        public static string RankName {
            get {
                return ResourceManager.GetString("RankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Time (Secs).
        /// </summary>
        public static string RefreshTimeSecs {
            get {
                return ResourceManager.GetString("RefreshTimeSecs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular.
        /// </summary>
        public static string Regular {
            get {
                return ResourceManager.GetString("Regular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote.
        /// </summary>
        public static string Remote {
            get {
                return ResourceManager.GetString("Remote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retroactively Give Points.
        /// </summary>
        public static string RetroactivelyGivePoints {
            get {
                return ResourceManager.GetString("RetroactivelyGivePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Bonuses.
        /// </summary>
        public static string RoleBonuses {
            get {
                return ResourceManager.GetString("RoleBonuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be a {0} to do this..
        /// </summary>
        public static string RoleErrorInsufficientRole {
            get {
                return ResourceManager.GetString("RoleErrorInsufficientRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same Age Rating.
        /// </summary>
        public static string SameAgeRating {
            get {
                return ResourceManager.GetString("SameAgeRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same Game.
        /// </summary>
        public static string SameGame {
            get {
                return ResourceManager.GetString("SameGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SameTeam.
        /// </summary>
        public static string SameTeam {
            get {
                return ResourceManager.GetString("SameTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save failed, attempting one more time....
        /// </summary>
        public static string SaveFailed {
            get {
                return ResourceManager.GetString("SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scene.
        /// </summary>
        public static string Scene {
            get {
                return ResourceManager.GetString("Scene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Criteria.
        /// </summary>
        public static string SearchCriteria {
            get {
                return ResourceManager.GetString("SearchCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Value.
        /// </summary>
        public static string SecondValue {
            get {
                return ResourceManager.GetString("SecondValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the type of command you would like to build:.
        /// </summary>
        public static string SelectTypeOfCommand {
            get {
                return ResourceManager.GetString("SelectTypeOfCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell Price.
        /// </summary>
        public static string SellPrice {
            get {
                return ResourceManager.GetString("SellPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send as Streamer.
        /// </summary>
        public static string SendAsStreamer {
            get {
                return ResourceManager.GetString("SendAsStreamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial.
        /// </summary>
        public static string Serial {
            get {
                return ResourceManager.GetString("Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop.
        /// </summary>
        public static string Shop {
            get {
                return ResourceManager.GetString("Shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop Command.
        /// </summary>
        public static string ShopCommand {
            get {
                return ResourceManager.GetString("ShopCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop Currency.
        /// </summary>
        public static string ShopCurrency {
            get {
                return ResourceManager.GetString("ShopCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Action.
        /// </summary>
        public static string SingleAction {
            get {
                return ResourceManager.GetString("SingleAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills Used.
        /// </summary>
        public static string SkillsUsed {
            get {
                return ResourceManager.GetString("SkillsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Streamer (&lt;10).
        /// </summary>
        public static string SmallStreamer {
            get {
                return ResourceManager.GetString("SmallStreamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song Request.
        /// </summary>
        public static string SongRequest {
            get {
                return ResourceManager.GetString("SongRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song Requests.
        /// </summary>
        public static string SongRequests {
            get {
                return ResourceManager.GetString("SongRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound.
        /// </summary>
        public static string Sound {
            get {
                return ResourceManager.GetString("Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spark Crystal.
        /// </summary>
        public static string SparkCrystal {
            get {
                return ResourceManager.GetString("SparkCrystal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spark Exempt.
        /// </summary>
        public static string SparkExempt {
            get {
                return ResourceManager.GetString("SparkExempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sparks Spent.
        /// </summary>
        public static string SparksSpent {
            get {
                return ResourceManager.GetString("SparksSpent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Identifier.
        /// </summary>
        public static string SpecialIdentifier {
            get {
                return ResourceManager.GetString("SpecialIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Identifier Name.
        /// </summary>
        public static string SpecialIdentifierName {
            get {
                return ResourceManager.GetString("SpecialIdentifierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Identifiers.
        /// </summary>
        public static string SpecialIdentifiers {
            get {
                return ResourceManager.GetString("SpecialIdentifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Identifiers Reference.
        /// </summary>
        public static string SpecialIdentifiersReference {
            get {
                return ResourceManager.GetString("SpecialIdentifiersReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        public static string Staff {
            get {
                return ResourceManager.GetString("Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream Boss.
        /// </summary>
        public static string StreamBoss {
            get {
                return ResourceManager.GetString("StreamBoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream Clip Playback.
        /// </summary>
        public static string StreamClip {
            get {
                return ResourceManager.GetString("StreamClip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streamer.
        /// </summary>
        public static string Streamer {
            get {
                return ResourceManager.GetString("Streamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streamer Account.
        /// </summary>
        public static string StreamerAccount {
            get {
                return ResourceManager.GetString("StreamerAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streaming Platform.
        /// </summary>
        public static string StreamingPlatform {
            get {
                return ResourceManager.GetString("StreamingPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streaming Software.
        /// </summary>
        public static string StreamingSoftware {
            get {
                return ResourceManager.GetString("StreamingSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streamlabs.
        /// </summary>
        public static string Streamlabs {
            get {
                return ResourceManager.GetString("Streamlabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streams Watched.
        /// </summary>
        public static string StreamsWatched {
            get {
                return ResourceManager.GetString("StreamsWatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream Title.
        /// </summary>
        public static string StreamTitle {
            get {
                return ResourceManager.GetString("StreamTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Age.
        /// </summary>
        public static string SubAge {
            get {
                return ResourceManager.GetString("SubAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Bonus.
        /// </summary>
        public static string SubBonus {
            get {
                return ResourceManager.GetString("SubBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriber.
        /// </summary>
        public static string Subscriber {
            get {
                return ResourceManager.GetString("Subscriber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subs Gifted.
        /// </summary>
        public static string SubsGifted {
            get {
                return ResourceManager.GetString("SubsGifted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subs Received.
        /// </summary>
        public static string SubsReceived {
            get {
                return ResourceManager.GetString("SubsReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagged In Chat.
        /// </summary>
        public static string TaggedInChat {
            get {
                return ResourceManager.GetString("TaggedInChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Name.
        /// </summary>
        public static string TeamName {
            get {
                return ResourceManager.GetString("TeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teen.
        /// </summary>
        public static string Teen {
            get {
                return ResourceManager.GetString("Teen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Command.
        /// </summary>
        public static string TestCommand {
            get {
                return ResourceManager.GetString("TestCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Color.
        /// </summary>
        public static string TextColor {
            get {
                return ResourceManager.GetString("TextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text To Speech.
        /// </summary>
        public static string TextToSpeech {
            get {
                return ResourceManager.GetString("TextToSpeech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticker Tape.
        /// </summary>
        public static string TickerTape {
            get {
                return ResourceManager.GetString("TickerTape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer.
        /// </summary>
        public static string Timer {
            get {
                return ResourceManager.GetString("Timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval (Minutes).
        /// </summary>
        public static string TimerInterval {
            get {
                return ResourceManager.GetString("TimerInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timers.
        /// </summary>
        public static string Timers {
            get {
                return ResourceManager.GetString("Timers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer Train.
        /// </summary>
        public static string TimerTrain {
            get {
                return ResourceManager.GetString("TimerTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Users.
        /// </summary>
        public static string TotalUsers {
            get {
                return ResourceManager.GetString("TotalUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade.
        /// </summary>
        public static string Trade {
            get {
                return ResourceManager.GetString("Trade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Command.
        /// </summary>
        public static string TradeCommand {
            get {
                return ResourceManager.GetString("TradeCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation.
        /// </summary>
        public static string Translation {
            get {
                return ResourceManager.GetString("Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TranslationBy {
            get {
                return ResourceManager.GetString("TranslationBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        public static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type To Add.
        /// </summary>
        public static string TypeToAdd {
            get {
                return ResourceManager.GetString("TypeToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungrouped.
        /// </summary>
        public static string Ungrouped {
            get {
                return ResourceManager.GetString("Ungrouped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock Command.
        /// </summary>
        public static string UnlockCommand {
            get {
                return ResourceManager.GetString("UnlockCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Channel.
        /// </summary>
        public static string UpdateChannel {
            get {
                return ResourceManager.GetString("UpdateChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload To.
        /// </summary>
        public static string UploadTo {
            get {
                return ResourceManager.GetString("UploadTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Joined Chat.
        /// </summary>
        public static string UserJoinedChat {
            get {
                return ResourceManager.GetString("UserJoinedChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Left Chat.
        /// </summary>
        public static string UserLeftChat {
            get {
                return ResourceManager.GetString("UserLeftChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Metrics.
        /// </summary>
        public static string UserMetrics {
            get {
                return ResourceManager.GetString("UserMetrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-Only Chat Commands.
        /// </summary>
        public static string UserOnlyChatCommands {
            get {
                return ResourceManager.GetString("UserOnlyChatCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Rank Changed.
        /// </summary>
        public static string UserRankChanged {
            get {
                return ResourceManager.GetString("UserRankChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Ranks.
        /// </summary>
        public static string UserRanks {
            get {
                return ResourceManager.GetString("UserRanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewers.
        /// </summary>
        public static string Viewers {
            get {
                return ResourceManager.GetString("Viewers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait.
        /// </summary>
        public static string Wait {
            get {
                return ResourceManager.GetString("Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch Time.
        /// </summary>
        public static string WatchTime {
            get {
                return ResourceManager.GetString("WatchTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Page.
        /// </summary>
        public static string WebPage {
            get {
                return ResourceManager.GetString("WebPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Request.
        /// </summary>
        public static string WebRequest {
            get {
                return ResourceManager.GetString("WebRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Show.
        /// </summary>
        public static string WebShow {
            get {
                return ResourceManager.GetString("WebShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        public static string Weekly {
            get {
                return ResourceManager.GetString("Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whisper.
        /// </summary>
        public static string Whisper {
            get {
                return ResourceManager.GetString("Whisper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whisper User (Optional).
        /// </summary>
        public static string WhisperUserOptional {
            get {
                return ResourceManager.GetString("WhisperUserOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wildcards.
        /// </summary>
        public static string Wildcards {
            get {
                return ResourceManager.GetString("Wildcards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly.
        /// </summary>
        public static string Yearly {
            get {
                return ResourceManager.GetString("Yearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
